# Testing datasets

In [57]:
import numpy as np
import pandas as pd
import sklearn.compose
import sklearn.preprocessing
import sklearn.model_selection

from lazyfca import LazyFCA

from utils import estimate_quality

In [58]:
pd.set_option('display.max_columns', None)

## Breast Cancer Wisconsin (Diagnostic)

https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic

In [59]:
data = pd.read_csv("./datasets/breast_cancer.csv")
data

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave_points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,1.1760,1.2560,7.673,158.70,0.010300,0.02891,0.05198,0.02454,0.01114,0.004239,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,0.7655,2.4630,5.203,99.04,0.005769,0.02423,0.03950,0.01678,0.01898,0.002498,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,0.4564,1.0750,3.425,48.55,0.005903,0.03731,0.04730,0.01557,0.01318,0.003892,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,0.7260,1.5950,5.772,86.22,0.006522,0.06158,0.07117,0.01664,0.02324,0.006185,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,0.3857,1.4280,2.548,19.15,0.007189,0.00466,0.00000,0.00000,0.02676,0.002783,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [60]:
data.diagnosis.value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [61]:
data['target'] = data['diagnosis'].map({'B': 0, 'M': 1})
data

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave_points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst,target
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,1
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,1
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,1
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,1
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,1.1760,1.2560,7.673,158.70,0.010300,0.02891,0.05198,0.02454,0.01114,0.004239,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,1
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,0.7655,2.4630,5.203,99.04,0.005769,0.02423,0.03950,0.01678,0.01898,0.002498,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,1
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,0.4564,1.0750,3.425,48.55,0.005903,0.03731,0.04730,0.01557,0.01318,0.003892,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,1
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,0.7260,1.5950,5.772,86.22,0.006522,0.06158,0.07117,0.01664,0.02324,0.006185,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,1
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,0.3857,1.4280,2.548,19.15,0.007189,0.00466,0.00000,0.00000,0.02676,0.002783,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,0

In [62]:
data = data.drop(columns = ['id', 'diagnosis'])

X = data.drop(columns = ["target"])
y = data["target"].to_numpy()
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(
    X, y, test_size = 0.1, stratify = y, random_state = 42
)

numeric = X.columns
categorical = list(set(X_train.columns) - set(numeric))
ct = sklearn.compose.ColumnTransformer(
    transformers = [
        ("numeric", 'passthrough', numeric),
        ("categorical", sklearn.preprocessing.OneHotEncoder(dtype = 'bool'), categorical)
    ]
)
X_train = pd.DataFrame(ct.fit_transform(X_train), columns = ct.get_feature_names_out())
X_test = pd.DataFrame(ct.transform(X_test), columns = ct.get_feature_names_out())

categorical = [ feature for feature in ct.get_feature_names_out() if feature.startswith("categorical__") ]
X_train[categorical] = X_train[categorical].astype(bool)
X_test[categorical] = X_test[categorical].astype(bool)

y_train = pd.Series(y_train)
y_test = pd.Series(y_test)

In [7]:
import itertools
import tqdm
import numpy
import pandas
import typing
import joblib

pos_supporters_covered = [1, 2, 3, 4, 5, 10, 25]
neg_supporters_covered = [1, 2, 3, 4, 5, 10, 25]
pos_supporter_opposer_ratio = [0.1, 0.25, 0.5, 0.75, 1.0, 2.5]
neg_supporter_opposer_ratio = [0.1, 0.25, 0.5, 0.75, 1.0, 2.5]
pos_weight = [0.5, 1.0, 1.5, 2.0]

values = list(itertools.product(pos_supporters_covered, neg_supporters_covered, pos_supporter_opposer_ratio, neg_supporter_opposer_ratio, pos_weight))

def process_params(pos_sup, neg_sup, pos_rat, neg_rat, pos_w):
    classifier = LazyFCA(
        pos_params=LazyFCA.Params(
            supporters_covered=pos_sup,
            supporter_opposer_ratio=pos_rat,
        ),
        neg_params=LazyFCA.Params(
            supporters_covered=neg_sup,
            supporter_opposer_ratio=neg_rat,
        ),
        pos_weight=pos_w
    )
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)
    metrics = estimate_quality(y_pred, y_test)
    return {
        'pos_sup': pos_sup,
        'neg_sup': neg_sup,
        'pos_rat': pos_rat,
        'neg_rat': neg_rat,
        'pos_w': pos_w,
        **metrics
    }

df_data = joblib.Parallel(n_jobs = -1)(
    joblib.delayed(process_params)(*params)
    for params in tqdm.tqdm(values)
)

# df_data = []
# for params in tqdm.tqdm(values):
#     res = process_params(*params)
#     df_data.append(res)

df = pandas.DataFrame(df_data)
df

100%|██████████| 57/57 [00:02<00:00, 25.76it/s]
100%|██████████| 57/57 [00:02<00:00, 25.55it/s]
100%|██████████| 57/57 [00:02<00:00, 25.41it/s]
100%|██████████| 57/57 [00:02<00:00, 24.96it/s]
100%|██████████| 57/57 [00:02<00:00, 24.85it/s]
100%|██████████| 57/57 [00:02<00:00, 25.06it/s]
100%|██████████| 57/57 [00:02<00:00, 24.92it/s]
100%|██████████| 57/57 [00:02<00:00, 24.37it/s]
100%|██████████| 57/57 [00:02<00:00, 24.08it/s]
100%|██████████| 57/57 [00:02<00:00, 23.71it/s]
100%|██████████| 57/57 [00:02<00:00, 24.67it/s]s]
100%|██████████| 57/57 [00:02<00:00, 23.63it/s]
100%|██████████| 57/57 [00:02<00:00, 23.83it/s]
100%|██████████| 57/57 [00:02<00:00, 22.47it/s]
100%|██████████| 57/57 [00:02<00:00, 22.72it/s]
100%|██████████| 57/57 [00:02<00:00, 23.58it/s]
100%|██████████| 57/57 [00:02<00:00, 21.23it/s]
100%|██████████| 57/57 [00:02<00:00, 21.28it/s]
100%|██████████| 57/57 [00:02<00:00, 21.83it/s]
100%|██████████| 57/57 [00:02<00:00, 20.67it/s]
100%|██████████| 57/57 [00:02<00:00, 24.13it/s]s]
100%|██████████| 57/57 [00:02<00:00, 25.74it/s]
100%|██████████| 57/57 [00:02<00:00, 23.75it/s]
100%|██████████| 57/57 [00:02<00:00, 24.96it/s]
100%|██████████| 57/57 [00:02<00:00, 23.97it/s]
100%|██████████| 57/57 [00:02<00:00, 24.96it/s]
100%|██████████| 57/57 [00:02<00:00, 25.29it/s]
100%|██████████| 57/57 [00:02<00:00, 25.70it/s]
100%|██████████| 57/57 [00:02<00:00, 23.96it/s]
100%|██████████| 57/57 [00:02<00:00, 21.95it/s]
100%|██████████| 57/57 [00:02<00:00, 22.52it/s] ]
100%|██████████| 57/57 [00:02<00:00, 22.67it/s]
100%|██████████| 57/57 [00:02<00:00, 23.60it/s]
100%|██████████| 57/57 [00:02<00:00, 23.81it/s]
100%|██████████| 57/57 [00:02<00:00, 22.95it/s]
100%|██████████| 57/57 [00:02<00:00, 24.85it/s]
100%|██████████| 57/57 [00:02<00:00, 23.57it/s]
100%|██████████| 57/57 [00:02<00:00, 23.92it/s]
100%|██████████| 57/57 [00:02<00:00, 24.69it/s]
100%|██████████| 57/57 [00:02<00:00, 22.60it/s]
100%|██████████| 57/57 [00:02<00:00, 25.09it/s] ]
100%|██████████| 57/57 [00:02<00:00, 23.79it/s]
100%|██████████| 57/57 [00:02<00:00, 23.25it/s]
100%|██████████| 57/57 [00:02<00:00, 22.65it/s]
100%|██████████| 57/57 [00:02<00:00, 23.95it/s]
100%|██████████| 57/57 [00:02<00:00, 23.23it/s]
100%|██████████| 57/57 [00:02<00:00, 23.68it/s]
100%|██████████| 57/57 [00:02<00:00, 23.93it/s]
100%|██████████| 57/57 [00:02<00:00, 25.21it/s]
100%|██████████| 57/57 [00:02<00:00, 24.02it/s]
100%|██████████| 57/57 [00:02<00:00, 24.36it/s]s]
100%|██████████| 57/57 [00:02<00:00, 25.22it/s]
100%|██████████| 57/57 [00:02<00:00, 24.78it/s]
100%|██████████| 57/57 [00:02<00:00, 24.96it/s]
100%|██████████| 57/57 [00:02<00:00, 23.41it/s]
100%|██████████| 57/57 [00:02<00:00, 24.82it/s]
100%|██████████| 57/57 [00:02<00:00, 25.16it/s]
100%|██████████| 57/57 [00:02<00:00, 26.71it/s]
100%|██████████| 57/57 [00:02<00:00, 25.92it/s]
100%|██████████| 57/57 [00:02<00:00, 23.96it/s]
100%|██████████| 57/57 [00:02<00:00, 25.17it/s] ]
100%|██████████| 57/57 [00:02<00:00, 24.78it/s]
100%|██████████| 57/57 [00:02<00:00, 21.98it/s]
100%|██████████| 57/57 [00:02<00:00, 26.09it/s]
100%|██████████| 57/57 [00:02<00:00, 24.89it/s]
100%|██████████| 57/57 [00:02<00:00, 22.64it/s]
100%|██████████| 57/57 [00:02<00:00, 25.29it/s]
100%|██████████| 57/57 [00:02<00:00, 26.09it/s]
100%|██████████| 57/57 [00:02<00:00, 23.62it/s]
100%|██████████| 57/57 [00:02<00:00, 23.54it/s]
100%|██████████| 57/57 [00:02<00:00, 21.86it/s]s]
100%|██████████| 57/57 [00:02<00:00, 20.03it/s]
100%|██████████| 57/57 [00:02<00:00, 20.56it/s]
100%|██████████| 57/57 [00:02<00:00, 22.58it/s]
100%|██████████| 57/57 [00:02<00:00, 21.52it/s]
100%|██████████| 57/57 [00:02<00:00, 21.53it/s]
100%|██████████| 57/57 [00:02<00:00, 22.21it/s]
100%|██████████| 57/57 [00:02<00:00, 22.28it/s]
100%|██████████| 57/57 [00:02<00:00, 23.66it/s]
100%|██████████| 57/57 [00:02<00:00, 22.98it/s]
100%|██████████| 57/57 [00:02<00:00, 21.29it/s] ]
100%|██████████| 57/57 [00:02<00:00, 22.47it/s]
100%|██████████| 57/57 [00:02<00:00, 21.03it/s]
100%|██████████| 57/57 [00:02<00:00, 21.51it/s]
100%|██████████| 57/57 [00:02<00:00, 22.78it/s]
100%|██████████| 57/57 [00:02<00:00, 21.36it/s]
100%|██████████| 57/57 [00:02<00:00, 21.87it/s]
100%|██████████| 57/57 [00:02<00:00, 20.85it/s]
100%|██████████| 57/57 [00:02<00:00, 22.15it/s]
100%|██████████| 57/57 [00:02<00:00, 22.59it/s]
100%|██████████| 57/57 [00:02<00:00, 24.20it/s]/s]
100%|██████████| 57/57 [00:02<00:00, 23.91it/s]
100%|██████████| 57/57 [00:02<00:00, 23.76it/s]
100%|██████████| 57/57 [00:02<00:00, 22.05it/s]
100%|██████████| 57/57 [00:02<00:00, 20.88it/s]
100%|██████████| 57/57 [00:02<00:00, 22.02it/s]
100%|██████████| 57/57 [00:02<00:00, 20.97it/s]
100%|██████████| 57/57 [00:02<00:00, 20.50it/s]
100%|██████████| 57/57 [00:02<00:00, 21.07it/s]
100%|██████████| 57/57 [00:02<00:00, 20.30it/s]
100%|██████████| 57/57 [00:02<00:00, 20.71it/s]/s]
100%|██████████| 57/57 [00:02<00:00, 20.52it/s]
100%|██████████| 57/57 [00:02<00:00, 19.99it/s]
100%|██████████| 57/57 [00:02<00:00, 20.99it/s]
100%|██████████| 57/57 [00:02<00:00, 20.75it/s]
100%|██████████| 57/57 [00:02<00:00, 20.06it/s]
100%|██████████| 57/57 [00:02<00:00, 20.77it/s]
100%|██████████| 57/57 [00:02<00:00, 19.95it/s]
100%|██████████| 57/57 [00:02<00:00, 21.28it/s]
100%|██████████| 57/57 [00:02<00:00, 20.90it/s]/s]
100%|██████████| 57/57 [00:02<00:00, 19.35it/s]
100%|██████████| 57/57 [00:02<00:00, 19.57it/s]
100%|██████████| 57/57 [00:03<00:00, 18.66it/s]
100%|██████████| 57/57 [00:02<00:00, 19.79it/s]
100%|██████████| 57/57 [00:03<00:00, 18.11it/s]
100%|██████████| 57/57 [00:03<00:00, 19.00it/s]
100%|██████████| 57/57 [00:02<00:00, 19.46it/s]
100%|██████████| 57/57 [00:02<00:00, 19.55it/s]
100%|██████████| 57/57 [00:02<00:00, 20.99it/s]/s]
100%|██████████| 57/57 [00:02<00:00, 21.56it/s]
100%|██████████| 57/57 [00:02<00:00, 20.26it/s]
100%|██████████| 57/57 [00:02<00:00, 20.12it/s]
100%|██████████| 57/57 [00:02<00:00, 19.41it/s]
100%|██████████| 57/57 [00:02<00:00, 21.71it/s]
100%|██████████| 57/57 [00:02<00:00, 20.05it/s]
100%|██████████| 57/57 [00:02<00:00, 23.45it/s]
100%|██████████| 57/57 [00:02<00:00, 20.87it/s]
100%|██████████| 57/57 [00:02<00:00, 22.27it/s]
100%|██████████| 57/57 [00:02<00:00, 22.99it/s]/s]
100%|██████████| 57/57 [00:02<00:00, 22.09it/s]
100%|██████████| 57/57 [00:02<00:00, 20.96it/s]
100%|██████████| 57/57 [00:02<00:00, 20.18it/s]
100%|██████████| 57/57 [00:02<00:00, 20.27it/s]
100%|██████████| 57/57 [00:02<00:00, 21.75it/s]
100%|██████████| 57/57 [00:02<00:00, 20.27it/s]
100%|██████████| 57/57 [00:02<00:00, 21.25it/s]
100%|██████████| 57/57 [00:02<00:00, 20.96it/s]
100%|██████████| 57/57 [00:02<00:00, 20.53it/s]/s]
100%|██████████| 57/57 [00:02<00:00, 22.69it/s]
100%|██████████| 57/57 [00:02<00:00, 21.75it/s]
100%|██████████| 57/57 [00:02<00:00, 20.77it/s]
100%|██████████| 57/57 [00:02<00:00, 22.43it/s]
100%|██████████| 57/57 [00:02<00:00, 21.69it/s]
100%|██████████| 57/57 [00:02<00:00, 20.51it/s]
100%|██████████| 57/57 [00:02<00:00, 20.58it/s]
100%|██████████| 57/57 [00:02<00:00, 22.22it/s]
100%|██████████| 57/57 [00:02<00:00, 20.52it/s]
100%|██████████| 57/57 [00:02<00:00, 21.61it/s]
100%|██████████| 57/57 [00:02<00:00, 22.69it/s]/s]
100%|██████████| 57/57 [00:02<00:00, 22.97it/s]
100%|██████████| 57/57 [00:03<00:00, 16.17it/s]
100%|██████████| 57/57 [00:03<00:00, 15.64it/s]
100%|██████████| 57/57 [00:03<00:00, 17.73it/s]
100%|██████████| 57/57 [00:02<00:00, 19.92it/s]
100%|██████████| 57/57 [00:02<00:00, 20.90it/s]
100%|██████████| 57/57 [00:02<00:00, 21.01it/s]
100%|██████████| 57/57 [00:02<00:00, 22.92it/s]
100%|██████████| 57/57 [00:02<00:00, 21.70it/s]/s]
100%|██████████| 57/57 [00:02<00:00, 23.28it/s]
100%|██████████| 57/57 [00:02<00:00, 23.74it/s]
100%|██████████| 57/57 [00:02<00:00, 21.64it/s]
100%|██████████| 57/57 [00:02<00:00, 20.70it/s]
100%|██████████| 57/57 [00:02<00:00, 24.87it/s]
100%|██████████| 57/57 [00:02<00:00, 22.76it/s]
100%|██████████| 57/57 [00:02<00:00, 21.81it/s]
100%|██████████| 57/57 [00:02<00:00, 23.29it/s]
100%|██████████| 57/57 [00:02<00:00, 23.24it/s]
100%|██████████| 57/57 [00:02<00:00, 21.77it/s]/s]
100%|██████████| 57/57 [00:02<00:00, 23.35it/s]
100%|██████████| 57/57 [00:02<00:00, 21.27it/s]
100%|██████████| 57/57 [00:02<00:00, 24.59it/s]
100%|██████████| 57/57 [00:02<00:00, 23.10it/s]
100%|██████████| 57/57 [00:02<00:00, 23.14it/s]
100%|██████████| 57/57 [00:02<00:00, 23.68it/s]
100%|██████████| 57/57 [00:02<00:00, 23.29it/s]
100%|██████████| 57/57 [00:02<00:00, 22.89it/s]
100%|██████████| 57/57 [00:02<00:00, 23.44it/s]
100%|██████████| 57/57 [00:02<00:00, 23.54it/s]/s]
100%|██████████| 57/57 [00:02<00:00, 22.67it/s]
100%|██████████| 57/57 [00:02<00:00, 22.34it/s]
100%|██████████| 57/57 [00:02<00:00, 22.39it/s]
100%|██████████| 57/57 [00:02<00:00, 21.23it/s]
100%|██████████| 57/57 [00:02<00:00, 24.12it/s]
100%|██████████| 57/57 [00:02<00:00, 22.26it/s]
100%|██████████| 57/57 [00:03<00:00, 18.02it/s]
100%|██████████| 57/57 [00:03<00:00, 17.23it/s]
100%|██████████| 57/57 [00:03<00:00, 16.95it/s]
100%|██████████| 57/57 [00:03<00:00, 18.33it/s]/s]
100%|██████████| 57/57 [00:03<00:00, 16.09it/s]
100%|██████████| 57/57 [00:03<00:00, 16.71it/s]
100%|██████████| 57/57 [00:02<00:00, 24.53it/s]
100%|██████████| 57/57 [00:03<00:00, 17.26it/s]
100%|██████████| 57/57 [00:03<00:00, 18.26it/s]
100%|██████████| 57/57 [00:03<00:00, 17.03it/s]
100%|██████████| 57/57 [00:03<00:00, 18.09it/s]
100%|██████████| 57/57 [00:03<00:00, 18.86it/s]
100%|██████████| 57/57 [00:03<00:00, 17.91it/s]
100%|██████████| 57/57 [00:03<00:00, 16.84it/s]/s]
100%|██████████| 57/57 [00:03<00:00, 17.33it/s]
100%|██████████| 57/57 [00:03<00:00, 17.52it/s]
100%|██████████| 57/57 [00:02<00:00, 21.21it/s]
100%|██████████| 57/57 [00:02<00:00, 21.11it/s]
100%|██████████| 57/57 [00:02<00:00, 23.03it/s]
100%|██████████| 57/57 [00:02<00:00, 21.70it/s]
100%|██████████| 57/57 [00:02<00:00, 21.79it/s]
100%|██████████| 57/57 [00:02<00:00, 21.33it/s]
100%|██████████| 57/57 [00:02<00:00, 22.54it/s]
100%|██████████| 57/57 [00:02<00:00, 21.14it/s]/s]
100%|██████████| 57/57 [00:02<00:00, 21.29it/s]]
100%|██████████| 57/57 [00:02<00:00, 22.89it/s]
100%|██████████| 57/57 [00:03<00:00, 17.17it/s]
100%|██████████| 57/57 [00:03<00:00, 18.08it/s]
100%|██████████| 57/57 [00:03<00:00, 17.06it/s]
100%|██████████| 57/57 [00:03<00:00, 17.70it/s]
100%|██████████| 57/57 [00:03<00:00, 17.18it/s]
100%|██████████| 57/57 [00:03<00:00, 17.18it/s]
100%|██████████| 57/57 [00:03<00:00, 17.92it/s]
100%|██████████| 57/57 [00:03<00:00, 17.29it/s]/s]
100%|██████████| 57/57 [00:03<00:00, 17.76it/s]
100%|██████████| 57/57 [00:02<00:00, 19.24it/s]
100%|██████████| 57/57 [00:02<00:00, 22.11it/s]
100%|██████████| 57/57 [00:02<00:00, 20.99it/s]
100%|██████████| 57/57 [00:02<00:00, 19.77it/s]
100%|██████████| 57/57 [00:03<00:00, 18.43it/s]
100%|██████████| 57/57 [00:02<00:00, 20.41it/s]
100%|██████████| 57/57 [00:02<00:00, 20.75it/s]
100%|██████████| 57/57 [00:02<00:00, 19.92it/s]
100%|██████████| 57/57 [00:02<00:00, 19.82it/s]]s]
100%|██████████| 57/57 [00:02<00:00, 19.76it/s]
100%|██████████| 57/57 [00:02<00:00, 20.89it/s]
100%|██████████| 57/57 [00:02<00:00, 19.75it/s]
100%|██████████| 57/57 [00:03<00:00, 16.90it/s]
100%|██████████| 57/57 [00:03<00:00, 18.46it/s]
100%|██████████| 57/57 [00:03<00:00, 18.69it/s]
100%|██████████| 57/57 [00:03<00:00, 18.15it/s]
100%|██████████| 57/57 [00:03<00:00, 17.17it/s]
100%|██████████| 57/57 [00:03<00:00, 17.94it/s]
100%|██████████| 57/57 [00:02<00:00, 20.45it/s]/s]
100%|██████████| 57/57 [00:02<00:00, 19.64it/s]
100%|██████████| 57/57 [00:02<00:00, 20.14it/s]
100%|██████████| 57/57 [00:02<00:00, 20.77it/s]
100%|██████████| 57/57 [00:02<00:00, 20.85it/s]
100%|██████████| 57/57 [00:02<00:00, 19.04it/s]
100%|██████████| 57/57 [00:02<00:00, 20.25it/s]
100%|██████████| 57/57 [00:02<00:00, 21.12it/s]
100%|██████████| 57/57 [00:02<00:00, 19.68it/s]/s]
100%|██████████| 57/57 [00:02<00:00, 19.74it/s]
100%|██████████| 57/57 [00:02<00:00, 19.41it/s]
100%|██████████| 57/57 [00:02<00:00, 21.22it/s]
100%|██████████| 57/57 [00:02<00:00, 19.79it/s]]
100%|██████████| 57/57 [00:02<00:00, 19.02it/s]
100%|██████████| 57/57 [00:03<00:00, 17.63it/s]
100%|██████████| 57/57 [00:02<00:00, 20.88it/s]
100%|██████████| 57/57 [00:02<00:00, 20.15it/s]
100%|██████████| 57/57 [00:02<00:00, 20.25it/s]/s]
100%|██████████| 57/57 [00:02<00:00, 20.68it/s]
100%|██████████| 57/57 [00:02<00:00, 19.34it/s]
100%|██████████| 57/57 [00:02<00:00, 21.44it/s]
100%|██████████| 57/57 [00:02<00:00, 20.24it/s]
100%|██████████| 57/57 [00:02<00:00, 19.85it/s]
100%|██████████| 57/57 [00:02<00:00, 20.38it/s]
100%|██████████| 57/57 [00:02<00:00, 21.46it/s]
100%|██████████| 57/57 [00:02<00:00, 22.91it/s]
100%|██████████| 57/57 [00:02<00:00, 23.36it/s]
100%|██████████| 57/57 [00:02<00:00, 22.65it/s]/s]
100%|██████████| 57/57 [00:02<00:00, 24.39it/s]
100%|██████████| 57/57 [00:02<00:00, 23.62it/s]
100%|██████████| 57/57 [00:02<00:00, 24.69it/s]
100%|██████████| 57/57 [00:02<00:00, 23.22it/s]
100%|██████████| 57/57 [00:02<00:00, 23.22it/s]
100%|██████████| 57/57 [00:02<00:00, 21.38it/s]]
100%|██████████| 57/57 [00:02<00:00, 23.83it/s]
100%|██████████| 57/57 [00:02<00:00, 22.19it/s]
100%|██████████| 57/57 [00:02<00:00, 22.74it/s]
100%|██████████| 57/57 [00:02<00:00, 23.48it/s]
100%|██████████| 57/57 [00:02<00:00, 22.48it/s]/s]
100%|██████████| 57/57 [00:02<00:00, 20.98it/s]
100%|██████████| 57/57 [00:02<00:00, 21.89it/s]
100%|██████████| 57/57 [00:02<00:00, 21.69it/s]
100%|██████████| 57/57 [00:02<00:00, 22.33it/s]
100%|██████████| 57/57 [00:02<00:00, 20.70it/s]
100%|██████████| 57/57 [00:02<00:00, 22.69it/s]
100%|██████████| 57/57 [00:02<00:00, 24.00it/s]
100%|██████████| 57/57 [00:02<00:00, 22.24it/s]
100%|██████████| 57/57 [00:02<00:00, 23.77it/s]
100%|██████████| 57/57 [00:02<00:00, 24.10it/s]/s]
100%|██████████| 57/57 [00:02<00:00, 24.49it/s]
100%|██████████| 57/57 [00:02<00:00, 23.03it/s]
100%|██████████| 57/57 [00:02<00:00, 24.32it/s]
100%|██████████| 57/57 [00:02<00:00, 24.13it/s]
100%|██████████| 57/57 [00:02<00:00, 23.54it/s]
100%|██████████| 57/57 [00:02<00:00, 23.20it/s]
100%|██████████| 57/57 [00:02<00:00, 23.64it/s]
100%|██████████| 57/57 [00:02<00:00, 22.98it/s]
100%|██████████| 57/57 [00:02<00:00, 25.45it/s]
100%|██████████| 57/57 [00:02<00:00, 22.98it/s]/s]
100%|██████████| 57/57 [00:02<00:00, 25.07it/s]
100%|██████████| 57/57 [00:02<00:00, 24.93it/s]
100%|██████████| 57/57 [00:02<00:00, 24.65it/s]
100%|██████████| 57/57 [00:02<00:00, 25.26it/s]
100%|██████████| 57/57 [00:02<00:00, 24.56it/s]]
100%|██████████| 57/57 [00:02<00:00, 24.83it/s]
100%|██████████| 57/57 [00:02<00:00, 25.47it/s]
100%|██████████| 57/57 [00:02<00:00, 27.08it/s]
100%|██████████| 57/57 [00:02<00:00, 26.56it/s]
100%|██████████| 57/57 [00:02<00:00, 26.83it/s]
100%|██████████| 57/57 [00:02<00:00, 26.70it/s]/s]
100%|██████████| 57/57 [00:02<00:00, 25.70it/s]
100%|██████████| 57/57 [00:02<00:00, 24.25it/s]
100%|██████████| 57/57 [00:02<00:00, 23.12it/s]
100%|██████████| 57/57 [00:02<00:00, 24.95it/s]
100%|██████████| 57/57 [00:02<00:00, 24.71it/s]]
100%|██████████| 57/57 [00:02<00:00, 24.54it/s]
100%|██████████| 57/57 [00:02<00:00, 25.41it/s]
100%|██████████| 57/57 [00:02<00:00, 25.20it/s]
100%|██████████| 57/57 [00:02<00:00, 25.44it/s]
100%|██████████| 57/57 [00:02<00:00, 25.01it/s]/s]
100%|██████████| 57/57 [00:02<00:00, 23.62it/s]
100%|██████████| 57/57 [00:02<00:00, 25.40it/s]
100%|██████████| 57/57 [00:02<00:00, 23.23it/s]
100%|██████████| 57/57 [00:02<00:00, 24.15it/s]
100%|██████████| 57/57 [00:02<00:00, 24.56it/s]
100%|██████████| 57/57 [00:02<00:00, 23.21it/s]
100%|██████████| 57/57 [00:02<00:00, 24.59it/s]
100%|██████████| 57/57 [00:02<00:00, 25.46it/s]
100%|██████████| 57/57 [00:02<00:00, 23.96it/s]
100%|██████████| 57/57 [00:02<00:00, 25.12it/s]/s]
100%|██████████| 57/57 [00:02<00:00, 26.35it/s]
100%|██████████| 57/57 [00:02<00:00, 24.35it/s]
100%|██████████| 57/57 [00:02<00:00, 24.63it/s]
100%|██████████| 57/57 [00:02<00:00, 24.52it/s]
100%|██████████| 57/57 [00:02<00:00, 25.43it/s]
100%|██████████| 57/57 [00:02<00:00, 23.64it/s]
100%|██████████| 57/57 [00:02<00:00, 23.04it/s]
100%|██████████| 57/57 [00:02<00:00, 22.94it/s]
100%|██████████| 57/57 [00:02<00:00, 25.09it/s]
100%|██████████| 57/57 [00:02<00:00, 22.77it/s]/s]
100%|██████████| 57/57 [00:02<00:00, 21.34it/s]
100%|██████████| 57/57 [00:02<00:00, 22.70it/s]
100%|██████████| 57/57 [00:02<00:00, 23.97it/s]
100%|██████████| 57/57 [00:02<00:00, 24.53it/s]
100%|██████████| 57/57 [00:02<00:00, 21.82it/s]
100%|██████████| 57/57 [00:02<00:00, 21.50it/s]
100%|██████████| 57/57 [00:02<00:00, 23.99it/s]
100%|██████████| 57/57 [00:02<00:00, 21.97it/s]
100%|██████████| 57/57 [00:02<00:00, 21.61it/s]
100%|██████████| 57/57 [00:02<00:00, 22.86it/s]
100%|██████████| 57/57 [00:02<00:00, 21.75it/s]/s]
100%|██████████| 57/57 [00:02<00:00, 23.64it/s]
100%|██████████| 57/57 [00:02<00:00, 21.59it/s]
100%|██████████| 57/57 [00:02<00:00, 21.95it/s]
100%|██████████| 57/57 [00:02<00:00, 20.36it/s]
100%|██████████| 57/57 [00:02<00:00, 20.94it/s]
100%|██████████| 57/57 [00:02<00:00, 22.68it/s]
100%|██████████| 57/57 [00:02<00:00, 21.31it/s]
100%|██████████| 57/57 [00:02<00:00, 22.46it/s]
100%|██████████| 57/57 [00:02<00:00, 19.06it/s]
100%|██████████| 57/57 [00:02<00:00, 20.98it/s]/s]
100%|██████████| 57/57 [00:02<00:00, 19.34it/s]
100%|██████████| 57/57 [00:02<00:00, 21.80it/s]
100%|██████████| 57/57 [00:02<00:00, 22.93it/s]
100%|██████████| 57/57 [00:02<00:00, 21.11it/s]
100%|██████████| 57/57 [00:02<00:00, 23.38it/s]
100%|██████████| 57/57 [00:02<00:00, 21.84it/s]
100%|██████████| 57/57 [00:02<00:00, 23.08it/s]
100%|██████████| 57/57 [00:02<00:00, 23.43it/s]
100%|██████████| 57/57 [00:02<00:00, 22.73it/s]/s]
100%|██████████| 57/57 [00:02<00:00, 24.85it/s]]
100%|██████████| 57/57 [00:02<00:00, 23.22it/s]
100%|██████████| 57/57 [00:02<00:00, 25.58it/s]
100%|██████████| 57/57 [00:02<00:00, 24.29it/s]
100%|██████████| 57/57 [00:02<00:00, 24.20it/s]
100%|██████████| 57/57 [00:02<00:00, 26.90it/s]
100%|██████████| 57/57 [00:02<00:00, 25.05it/s]
100%|██████████| 57/57 [00:02<00:00, 25.85it/s]
100%|██████████| 57/57 [00:02<00:00, 27.35it/s]
100%|██████████| 57/57 [00:02<00:00, 24.02it/s]/s]
100%|██████████| 57/57 [00:02<00:00, 28.38it/s]
100%|██████████| 57/57 [00:02<00:00, 28.02it/s]
100%|██████████| 57/57 [00:02<00:00, 25.53it/s]
100%|██████████| 57/57 [00:02<00:00, 28.22it/s]]
100%|██████████| 57/57 [00:02<00:00, 26.03it/s]
100%|██████████| 57/57 [00:01<00:00, 30.10it/s]
100%|██████████| 57/57 [00:02<00:00, 25.40it/s]
100%|██████████| 57/57 [00:02<00:00, 25.44it/s]
100%|██████████| 57/57 [00:02<00:00, 23.39it/s]/s]
100%|██████████| 57/57 [00:02<00:00, 26.51it/s]]
100%|██████████| 57/57 [00:02<00:00, 25.46it/s]
100%|██████████| 57/57 [00:02<00:00, 23.21it/s]
100%|██████████| 57/57 [00:02<00:00, 24.99it/s]
100%|██████████| 57/57 [00:02<00:00, 25.05it/s]
100%|██████████| 57/57 [00:02<00:00, 23.75it/s]
100%|██████████| 57/57 [00:02<00:00, 22.81it/s]
100%|██████████| 57/57 [00:02<00:00, 27.34it/s]
100%|██████████| 57/57 [00:02<00:00, 24.14it/s]
100%|██████████| 57/57 [00:02<00:00, 23.86it/s]/s]
100%|██████████| 57/57 [00:02<00:00, 21.27it/s]
100%|██████████| 57/57 [00:02<00:00, 21.14it/s]
100%|██████████| 57/57 [00:02<00:00, 21.12it/s]
100%|██████████| 57/57 [00:02<00:00, 22.53it/s]
100%|██████████| 57/57 [00:02<00:00, 28.33it/s]
100%|██████████| 57/57 [00:02<00:00, 23.83it/s]
100%|██████████| 57/57 [00:02<00:00, 24.89it/s]
100%|██████████| 57/57 [00:02<00:00, 23.30it/s]
100%|██████████| 57/57 [00:02<00:00, 24.13it/s]
100%|██████████| 57/57 [00:02<00:00, 26.42it/s]/s]
100%|██████████| 57/57 [00:02<00:00, 25.38it/s]
100%|██████████| 57/57 [00:02<00:00, 24.50it/s]
100%|██████████| 57/57 [00:02<00:00, 24.17it/s]
100%|██████████| 57/57 [00:02<00:00, 26.29it/s]
100%|██████████| 57/57 [00:02<00:00, 26.13it/s]
100%|██████████| 57/57 [00:02<00:00, 26.47it/s]
100%|██████████| 57/57 [00:02<00:00, 24.44it/s]
100%|██████████| 57/57 [00:02<00:00, 25.76it/s]

,pos_sup,neg_sup,pos_rat,neg_rat,pos_w,Accuracy,Precision,Recall,AUC-ROC,F1-score,True Positive,True Negative,False Positive,False Negative,True Negative Rate (Specificity),Negative Predictive Value,False Positive Rate,False Discovery Rate
0,1,1,0.1,0.10,0.5,0.631579,0.000000,0.0,0.50000,0.000000,0,36,0,21,1.0,0.631579,0.0,0.000000
1,1,1,0.1,0.10,1.0,0.631579,0.000000,0.0,0.50000,0.000000,0,36,0,21,1.0,0.631579,0.0,0.000000
2,1,1,0.1,0.10,1.5,0.631579,0.000000,0.0,0.50000,0.000000,0,36,0,21,1.0,0.631579,0.0,0.000000
3,1,1,0.1,0.10,2.0,0.368421,0.368421,1.0,0.50000,0.538462,21,0,36,0,0.0,0.000000,1.0,0.631579
4,1,1,0.1,0.25,0.5,0.631579,0.000000,0.0,0.52381,0.000000,0,36,0,21,1.0,0.631579,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7051,25,25,2.5,1.00,2.0,0.631579,0.000000,0.0,0.50000,0.000000,0,36,0,21,1.0,0.631579,0.0,0.000000
7052,25,25,2.5,2.50,0.5,0.631579,0.000000,0.0,0.50000,0.000000,0,36,0,21,1.0,0.631579,0.0,0.000000
7053,25,25,2.5,2.50,1.0,0.631579,0.000000,0.0,0.50000,0.000000,0,36,0,21,1.0,0.631579,0.0,0.000000
7054,25,25,2.5,2.50,1.5,0.631579,0.000000,0.0,0.50000,0.000000,0,36,0,21,1.0,0.631579,0.0,0.000000
7055,25,25,2.5,2.50,2.0,0.631579,0.000000,0.0,0.50000,0.000000,0,36,0,21,1.0,0.631579,0.0,0.000000

In [8]:
df.sort_values(by = 'F1-score', ascending = False).head(20)

,pos_sup,neg_sup,pos_rat,neg_rat,pos_w,Accuracy,Precision,Recall,AUC-ROC,F1-score,True Positive,True Negative,False Positive,False Negative,True Negative Rate (Specificity),Negative Predictive Value,False Positive Rate,False Discovery Rate
139,1,1,2.50,1.00,2.0,0.385965,0.375000,1.0,0.641534,0.545455,21,1,35,0,0.027778,1.0,0.972222,0.625000
127,1,1,2.50,0.25,2.0,0.385965,0.375000,1.0,0.623677,0.545455,21,1,35,0,0.027778,1.0,0.972222,0.625000
131,1,1,2.50,0.50,2.0,0.385965,0.375000,1.0,0.623677,0.545455,21,1,35,0,0.027778,1.0,0.972222,0.625000
123,1,1,2.50,0.10,2.0,0.385965,0.375000,1.0,0.605820,0.545455,21,1,35,0,0.027778,1.0,0.972222,0.625000
143,1,1,2.50,2.50,2.0,0.385965,0.375000,1.0,0.677249,0.545455,21,1,35,0,0.027778,1.0,0.972222,0.625000
135,1,1,2.50,0.75,2.0,0.385965,0.375000,1.0,0.641534,0.545455,21,1,35,0,0.027778,1.0,0.972222,0.625000
741,1,10,0.10,2.50,1.0,0.368421,0.368421,1.0,0.500000,0.538462,21,0,36,0,0.000000,0.0,1.000000,0.631579
676,1,5,1.00,0.25,0.5,0.368421,0.368421,1.0,0.428571,0.538462,21,0,36,0,0.000000,0.0,1.000000,0.631579
675,1,5,1.00,0.10,2.0,0.368421,0.368421,1.0,0.428571,0.538462,21,0,36,0,0.000000,0.0,1.000000,0.631579
674,1,5,1.00,0.10,1.5,0.368421,0.368421,1.0,0.428571,0.538462,21,0,36,0,0.000000,0.0,1.000000,0.631579
673,1,5,1.00,0.10,1.0,0.368421,0.368421,1.0,0.428571,0.538462,21,0,36,0,0.000000,0.0,1.000000,0.631579
672,1,5,1.00,0.10,0.5,0.368421,0.368421,1.0,0.428571,0.538462,21,0,36,0,0.000000,0.0,1.000000,0.631579
670,1,5,0.75,2.50,1.5,0.368421,0.368421,1.0,0.428571,0.538462,21,0,36,0,0.000000,0.0,1.000000,0.631579
671,1,5,0.75,2.50,2.0,0.368421,0.368421,1.0,0.428571,0.538462,21,0,36,0,0.000000,0.0,1.000000,0.631579
678,1,5,1.00,0.25,1.5,0.368421,0.368421,1.0,0.428571,0.538462,21,0,36,0,0.000000,0.0,1.000000,0.631579
669,1,5,0.75,2.50,1.0,0.368421,0.368421,1.0,0.428571,0.538462,21,0,36,0,0.000000,0.0,1.000000,0.631579
668,1,5,0.75,2.50,0.5,0.368421,0.368421,1.0,0.428571,0.538462,21,0,36,0,0.000000,0.0,1.000000,0.631579
667,1,5,0.75,1.00,2.0,0.368421,0.368421,1.0,0.428571,0.538462,21,0,36,0,0.000000,0.0,1.000000,0.631579
666,1,5,0.75,1.00,1.5,0.368421,0.368421,1.0,0.428571,0.538462,21,0,36,0,0.000000,0.0,1.000000,0.631579
677,1,5,1.00,0.25,1.0,0.368421,0.368421,1.0,0.428571,0.538462,21,0,36,0,0.000000,0.0,1.000000,0.631579

In [82]:
classifier = LazyFCA(
    pos_params=LazyFCA.Params(
        supporters_covered=1,
        supporter_opposer_ratio=3.0,
    ),
    neg_params=LazyFCA.Params(
        supporters_covered=1,
        supporter_opposer_ratio=9.0,
    ),
    pos_weight=2.0
)
classifier.fit(X_train, y_train)

In [83]:
y_pred = classifier.predict(X_test)

100%|██████████| 57/57 [00:00<00:00, 239.48it/s]

In [84]:
base_metrics = estimate_quality(y_pred, y_test)
base_metrics

{'Accuracy': 0.38596491228070173,
 'Precision': 0.375,
 'Recall': 1.0,
 'AUC-ROC': 0.69510582010582,
 'F1-score': 0.5454545454545454,
 'True Positive': np.int64(21),
 'True Negative': np.int64(1),
 'False Positive': np.int64(35),
 'False Negative': np.int64(0),
 'True Negative Rate (Specificity)': np.float64(0.027777777777777776),
 'Negative Predictive Value': np.float64(1.0),
 'False Positive Rate': np.float64(0.9722222222222222),
 'False Discovery Rate': np.float64(0.625)}

## Rice dataset

In [85]:
data = pd.read_csv("./datasets/rice.csv")
data

,Area,Perimeter,Major_Axis_Length,Minor_Axis_Length,Eccentricity,Convex_Area,Extent,Class
0,15231,525.578979,229.749878,85.093788,0.928882,15617,0.572896,Cammeo
1,14656,494.311005,206.020065,91.730972,0.895405,15072,0.615436,Cammeo
2,14634,501.122009,214.106781,87.768288,0.912118,14954,0.693259,Cammeo
3,13176,458.342987,193.337387,87.448395,0.891861,13368,0.640669,Cammeo
4,14688,507.166992,211.743378,89.312454,0.906691,15262,0.646024,Cammeo
...,...,...,...,...,...,...,...,...
3805,11441,415.858002,170.486771,85.756592,0.864280,11628,0.681012,Osmancik
3806,11625,421.390015,167.714798,89.462570,0.845850,11904,0.694279,Osmancik
3807,12437,442.498993,183.572922,86.801979,0.881144,12645,0.626739,Osmancik
3808,9882,392.296997,161.193985,78.210480,0.874406,10097,0.659064,Osmancik
3809,11434,404.709991,161.079269,90.868195,0.825692,11591,0.802949,Osmancik

In [86]:
data.Class.value_counts()

Class
Osmancik    2180
Cammeo      1630
Name: count, dtype: int64

In [87]:
data['Class'] = data['Class'].map({'Osmancik': 0, 'Cammeo': 1})
data

,Area,Perimeter,Major_Axis_Length,Minor_Axis_Length,Eccentricity,Convex_Area,Extent,Class
0,15231,525.578979,229.749878,85.093788,0.928882,15617,0.572896,1
1,14656,494.311005,206.020065,91.730972,0.895405,15072,0.615436,1
2,14634,501.122009,214.106781,87.768288,0.912118,14954,0.693259,1
3,13176,458.342987,193.337387,87.448395,0.891861,13368,0.640669,1
4,14688,507.166992,211.743378,89.312454,0.906691,15262,0.646024,1
...,...,...,...,...,...,...,...,...
3805,11441,415.858002,170.486771,85.756592,0.864280,11628,0.681012,0
3806,11625,421.390015,167.714798,89.462570,0.845850,11904,0.694279,0
3807,12437,442.498993,183.572922,86.801979,0.881144,12645,0.626739,0
3808,9882,392.296997,161.193985,78.210480,0.874406,10097,0.659064,0
3809,11434,404.709991,161.079269,90.868195,0.825692,11591,0.802949,0

In [88]:
X = data.drop(columns = ["Class"])
y = data["Class"].to_numpy()
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(
    X, y, test_size = 0.1, stratify = y, random_state = 42
)

numeric = X.columns
categorical = list(set(X_train.columns) - set(numeric))
ct = sklearn.compose.ColumnTransformer(
    transformers = [
        ("numeric", 'passthrough', numeric),
        ("categorical", sklearn.preprocessing.OneHotEncoder(dtype = 'bool'), categorical)
    ]
)
X_train = pd.DataFrame(ct.fit_transform(X_train), columns = ct.get_feature_names_out())
X_test = pd.DataFrame(ct.transform(X_test), columns = ct.get_feature_names_out())

categorical = [ feature for feature in ct.get_feature_names_out() if feature.startswith("categorical__") ]
X_train[categorical] = X_train[categorical].astype(bool)
X_test[categorical] = X_test[categorical].astype(bool)

y_train = pd.Series(y_train)
y_test = pd.Series(y_test)

In [56]:
# import itertools
# import tqdm
# import numpy
# import pandas
# import typing
# import joblib

# pos_supporters_covered = [1, 2, 3, 4, 5, 10, 25]
# neg_supporters_covered = [1, 2, 3, 4, 5, 10, 25]
# pos_supporter_opposer_ratio = [0.1, 0.25, 0.5, 0.75, 1.0, 2.5]
# neg_supporter_opposer_ratio = [0.1, 0.25, 0.5, 0.75, 1.0, 2.5]
# pos_weight = [0.5, 1.0, 1.5, 2.0]

# values = list(itertools.product(pos_supporters_covered, neg_supporters_covered, pos_supporter_opposer_ratio, neg_supporter_opposer_ratio, pos_weight))

# def process_params(pos_sup, neg_sup, pos_rat, neg_rat, pos_w):
#     classifier = LazyFCA(
#         pos_params=LazyFCA.Params(
#             supporters_covered=pos_sup,
#             supporter_opposer_ratio=pos_rat,
#         ),
#         neg_params=LazyFCA.Params(
#             supporters_covered=neg_sup,
#             supporter_opposer_ratio=neg_rat,
#         ),
#         pos_weight=pos_w
#     )
#     classifier.fit(X_train, y_train)
#     y_pred = classifier.predict(X_test, n_jobs=1)
#     metrics = estimate_quality(y_pred, y_test)
#     return {
#         'pos_sup': pos_sup,
#         'neg_sup': neg_sup,
#         'pos_rat': pos_rat,
#         'neg_rat': neg_rat,
#         'pos_w': pos_w,
#         **metrics
#     }

# df_data = joblib.Parallel(n_jobs = -1)(
#     joblib.delayed(process_params)(*params)
#     for params in tqdm.tqdm(values)
# )
# df = pandas.DataFrame(df_data)
# df

In [22]:
df = pandas.DataFrame(df_data)
df

,pos_sup,neg_sup,pos_rat,neg_rat,pos_w,Accuracy,Precision,Recall,AUC-ROC,F1-score,True Positive,True Negative,False Positive,False Negative,True Negative Rate (Specificity),Negative Predictive Value,False Positive Rate,False Discovery Rate
0,1,1,0.1,0.10,0.5,0.631579,0.000000,0.0,0.50000,0.000000,0,36,0,21,1.0,0.631579,0.0,0.000000
1,1,1,0.1,0.10,1.0,0.631579,0.000000,0.0,0.50000,0.000000,0,36,0,21,1.0,0.631579,0.0,0.000000
2,1,1,0.1,0.10,1.5,0.631579,0.000000,0.0,0.50000,0.000000,0,36,0,21,1.0,0.631579,0.0,0.000000
3,1,1,0.1,0.10,2.0,0.368421,0.368421,1.0,0.50000,0.538462,21,0,36,0,0.0,0.000000,1.0,0.631579
4,1,1,0.1,0.25,0.5,0.631579,0.000000,0.0,0.52381,0.000000,0,36,0,21,1.0,0.631579,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7051,25,25,2.5,1.00,2.0,0.631579,0.000000,0.0,0.50000,0.000000,0,36,0,21,1.0,0.631579,0.0,0.000000
7052,25,25,2.5,2.50,0.5,0.631579,0.000000,0.0,0.50000,0.000000,0,36,0,21,1.0,0.631579,0.0,0.000000
7053,25,25,2.5,2.50,1.0,0.631579,0.000000,0.0,0.50000,0.000000,0,36,0,21,1.0,0.631579,0.0,0.000000
7054,25,25,2.5,2.50,1.5,0.631579,0.000000,0.0,0.50000,0.000000,0,36,0,21,1.0,0.631579,0.0,0.000000
7055,25,25,2.5,2.50,2.0,0.631579,0.000000,0.0,0.50000,0.000000,0,36,0,21,1.0,0.631579,0.0,0.000000

In [23]:
df.sort_values(by = 'F1-score', ascending = False).head(20)

,pos_sup,neg_sup,pos_rat,neg_rat,pos_w,Accuracy,Precision,Recall,AUC-ROC,F1-score,True Positive,True Negative,False Positive,False Negative,True Negative Rate (Specificity),Negative Predictive Value,False Positive Rate,False Discovery Rate
139,1,1,2.50,1.00,2.0,0.385965,0.375000,1.0,0.641534,0.545455,21,1,35,0,0.027778,1.0,0.972222,0.625000
127,1,1,2.50,0.25,2.0,0.385965,0.375000,1.0,0.623677,0.545455,21,1,35,0,0.027778,1.0,0.972222,0.625000
131,1,1,2.50,0.50,2.0,0.385965,0.375000,1.0,0.623677,0.545455,21,1,35,0,0.027778,1.0,0.972222,0.625000
123,1,1,2.50,0.10,2.0,0.385965,0.375000,1.0,0.605820,0.545455,21,1,35,0,0.027778,1.0,0.972222,0.625000
143,1,1,2.50,2.50,2.0,0.385965,0.375000,1.0,0.677249,0.545455,21,1,35,0,0.027778,1.0,0.972222,0.625000
135,1,1,2.50,0.75,2.0,0.385965,0.375000,1.0,0.641534,0.545455,21,1,35,0,0.027778,1.0,0.972222,0.625000
741,1,10,0.10,2.50,1.0,0.368421,0.368421,1.0,0.500000,0.538462,21,0,36,0,0.000000,0.0,1.000000,0.631579
676,1,5,1.00,0.25,0.5,0.368421,0.368421,1.0,0.428571,0.538462,21,0,36,0,0.000000,0.0,1.000000,0.631579
675,1,5,1.00,0.10,2.0,0.368421,0.368421,1.0,0.428571,0.538462,21,0,36,0,0.000000,0.0,1.000000,0.631579
674,1,5,1.00,0.10,1.5,0.368421,0.368421,1.0,0.428571,0.538462,21,0,36,0,0.000000,0.0,1.000000,0.631579
673,1,5,1.00,0.10,1.0,0.368421,0.368421,1.0,0.428571,0.538462,21,0,36,0,0.000000,0.0,1.000000,0.631579
672,1,5,1.00,0.10,0.5,0.368421,0.368421,1.0,0.428571,0.538462,21,0,36,0,0.000000,0.0,1.000000,0.631579
670,1,5,0.75,2.50,1.5,0.368421,0.368421,1.0,0.428571,0.538462,21,0,36,0,0.000000,0.0,1.000000,0.631579
671,1,5,0.75,2.50,2.0,0.368421,0.368421,1.0,0.428571,0.538462,21,0,36,0,0.000000,0.0,1.000000,0.631579
678,1,5,1.00,0.25,1.5,0.368421,0.368421,1.0,0.428571,0.538462,21,0,36,0,0.000000,0.0,1.000000,0.631579
669,1,5,0.75,2.50,1.0,0.368421,0.368421,1.0,0.428571,0.538462,21,0,36,0,0.000000,0.0,1.000000,0.631579
668,1,5,0.75,2.50,0.5,0.368421,0.368421,1.0,0.428571,0.538462,21,0,36,0,0.000000,0.0,1.000000,0.631579
667,1,5,0.75,1.00,2.0,0.368421,0.368421,1.0,0.428571,0.538462,21,0,36,0,0.000000,0.0,1.000000,0.631579
666,1,5,0.75,1.00,1.5,0.368421,0.368421,1.0,0.428571,0.538462,21,0,36,0,0.000000,0.0,1.000000,0.631579
677,1,5,1.00,0.25,1.0,0.368421,0.368421,1.0,0.428571,0.538462,21,0,36,0,0.000000,0.0,1.000000,0.631579

In [106]:
classifier = LazyFCA(
    pos_params=LazyFCA.Params(
        supporters_covered=1,
        supporter_opposer_ratio=1.0,
        # matthews_correlation=0.15,
    ),
    neg_params=LazyFCA.Params(
        supporters_covered=2,
        supporter_opposer_ratio=1.7,
        # matthews_correlation=0.15,
    ),
    pos_weight=1.0
)
classifier.fit(X_train, y_train)

In [107]:
y_pred = classifier.predict(X_test)

100%|██████████| 381/381 [00:10<00:00, 35.45it/s]

In [108]:
base_metrics = estimate_quality(y_pred, y_test)
base_metrics

{'Accuracy': 0.9212598425196851,
 'Precision': 0.965034965034965,
 'Recall': 0.8466257668711656,
 'AUC-ROC': 0.9813136714132944,
 'F1-score': 0.9019607843137255,
 'True Positive': np.int64(138),
 'True Negative': np.int64(213),
 'False Positive': np.int64(5),
 'False Negative': np.int64(25),
 'True Negative Rate (Specificity)': np.float64(0.9770642201834863),
 'Negative Predictive Value': np.float64(0.8949579831932774),
 'False Positive Rate': np.float64(0.022935779816513763),
 'False Discovery Rate': np.float64(0.03496503496503497)}

In [111]:
score = classifier.explain_sample(X_test.iloc[52]).display()
score[score['Type'] == 'POSITIVE'].sort_values(by = 'WRAcc', ascending = False)

,Hypothesis,Type,Supporters,Opposers,Supporters covered,Opposers covered,Supporters to opposers ratio,Support,Error rate,Precision,Lift,WRAcc,Balanced precision proxy,Youden's J,Matthews correlation,Information gain,Gini gain,Log odds ratio,Chi squared,G-test
120,"[12433.0, 15306.0]; [442.48199462890625, 524.6...",POSITIVE,1467,1962,286,71,4.028169,0.194956,0.036188,0.801120,1.872558,0.038865,0.158768,0.158768,0.257207,0.354274,0.033058,4.006993,953.326645,-1074.609375
224,"[12433.0, 14944.0]; [442.48199462890625, 512.1...",POSITIVE,1467,1962,333,138,2.413043,0.226994,0.070336,0.707006,1.652573,0.038348,0.156657,0.156657,0.225168,0.404396,0.084199,2.407942,886.295379,-1253.623953
452,"[12433.0, 14294.0]; [442.48199462890625, 514.4...",POSITIVE,1467,1962,284,106,2.679245,0.193592,0.054027,0.728205,1.702124,0.034164,0.139566,0.139566,0.217493,0.370419,0.067656,2.671362,959.707041,-1138.823485
296,"[12433.0, 14359.0]; [442.48199462890625, 506.0...",POSITIVE,1467,1962,273,103,2.650485,0.186094,0.052497,0.726064,1.697119,0.032703,0.133597,0.133597,0.211545,0.364012,0.067608,2.642512,977.210918,-1118.596204
613,"[12433.0, 14709.0]; [442.48199462890625, 515.8...",POSITIVE,1467,1962,249,85,2.929412,0.169734,0.043323,0.745509,1.742570,0.030944,0.126411,0.126411,0.210934,0.343398,0.055960,2.918129,1014.946271,-1049.477069
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
633,"[12333.0, 12433.0]; [442.48199462890625, 463.1...",POSITIVE,1467,1962,1,1,1.000000,0.000682,0.000510,0.500000,1.168712,0.000042,0.000172,0.000172,0.003524,0.005480,0.001019,1.000000,1465.001191,-16.581440
273,"[12433.0, 12491.0]; [442.48199462890625, 457.1...",POSITIVE,1467,1962,1,1,1.000000,0.000682,0.000510,0.500000,1.168712,0.000042,0.000172,0.000172,0.003524,0.005480,0.001019,1.000000,1465.001191,-16.581440
332,"[12433.0, 12720.0]; [442.48199462890625, 449.6...",POSITIVE,1467,1962,1,1,1.000000,0.000682,0.000510,0.500000,1.168712,0.000042,0.000172,0.000172,0.003524,0.005480,0.001019,1.000000,1465.001191,-16.581440
539,"[12433.0, 13777.0]; [442.48199462890625, 480.8...",POSITIVE,1467,1962,1,1,1.000000,0.000682,0.000510,0.500000,1.168712,0.000042,0.000172,0.000172,0.003524,0.005480,0.001019,1.000000,1465.001191,-16.581440
337,"[12433.0, 12752.0]; [442.48199462890625, 462.3...",POSITIVE,1467,1962,1,1,1.000000,0.000682,0.000510,0.500000,1.168712,0.000042,0.000172,0.000172,0.003524,0.005480,0.001019,1.000000,1465.001191,-16.581440

In [112]:
score[score['Type'] == 'NEGATIVE'].sort_values(by = 'WRAcc', ascending = False)

,Hypothesis,Type,Supporters,Opposers,Supporters covered,Opposers covered,Supporters to opposers ratio,Support,Error rate,Precision,Lift,WRAcc,Balanced precision proxy,Youden's J,Matthews correlation,Information gain,Gini gain,Log odds ratio,Chi squared,G-test
2090,"[9544.0, 12433.0]; [386.56298828125, 442.48199...",NEGATIVE,1962,1467,362,0,inf,0.184506,0.000000,1.000000,1.747706,0.045165,0.184506,0.184506,0.297073,0.311828,-0.034042,725.000000,1304.791030,-1223.614610
1909,"[9584.0, 12433.0]; [390.0039978027344, 442.481...",NEGATIVE,1962,1467,352,0,inf,0.179409,0.000000,1.000000,1.747706,0.043918,0.179409,0.179409,0.292464,0.308240,-0.032188,705.000000,1321.151886,-1209.534279
2076,"[9733.0, 12433.0]; [396.6539916992187, 442.481...",NEGATIVE,1962,1467,336,0,inf,0.171254,0.000000,1.000000,1.747706,0.041921,0.171254,0.171254,0.285000,0.302196,-0.029328,673.000000,1347.541284,-1185.816899
1092,"[8499.0, 12433.0]; [370.4460144042969, 442.481...",NEGATIVE,1962,1467,322,0,inf,0.164118,0.000000,1.000000,1.747706,0.040175,0.164118,0.164118,0.278370,0.296589,-0.026935,645.000000,1370.846075,-1163.816253
1658,"[7833.0, 12433.0]; [373.1570129394531, 442.481...",NEGATIVE,1962,1467,313,0,inf,0.159531,0.000000,1.000000,1.747706,0.039052,0.159531,0.159531,0.274056,0.292822,-0.025450,627.000000,1385.933231,-1149.033297
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2138,"[12433.0, 12826.0]; [442.48199462890625, 452.8...",NEGATIVE,1962,1467,3,1,3.0,0.001529,0.000682,0.750000,1.310780,0.000207,0.000847,0.000847,0.012283,0.010594,0.001361,2.333333,1956.005269,-40.897962
2250,"[12433.0, 12571.0]; [442.48199462890625, 453.3...",NEGATIVE,1962,1467,3,1,3.0,0.001529,0.000682,0.750000,1.310780,0.000207,0.000847,0.000847,0.012283,0.010594,0.001361,2.333333,1956.005269,-40.897962
744,"[12433.0, 12695.0]; [442.48199462890625, 447.8...",NEGATIVE,1962,1467,2,1,2.0,0.001019,0.000682,0.666667,1.165138,0.000083,0.000338,0.000338,0.005651,0.007703,0.001362,1.666667,1958.002720,-29.553608
1366,"[12433.0, 12599.0]; [442.48199462890625, 450.2...",NEGATIVE,1962,1467,2,1,2.0,0.001019,0.000682,0.666667,1.165138,0.000083,0.000338,0.000338,0.005651,0.007703,0.001362,1.666667,1958.002720,-29.553608
1025,"[12378.0, 12433.0]; [442.48199462890625, 459.9...",NEGATIVE,1962,1467,2,1,2.0,0.001019,0.000682,0.666667,1.165138,0.000083,0.000338,0.000338,0.005651,0.007703,0.001362,1.666667,1958.002720,-29.553608

In [40]:
import catboost
cb = catboost.CatBoostClassifier(n_estimators=2500)
cb.fit(X_train, y_train)
estimate_quality(cb.predict_proba(X_test), y_test)

Learning rate set to 0.007526
0:	learn: 0.6806171	total: 57.1ms	remaining: 2m 22s
1:	learn: 0.6709295	total: 58.1ms	remaining: 1m 12s
2:	learn: 0.6596443	total: 59.2ms	remaining: 49.3s
3:	learn: 0.6496490	total: 60.3ms	remaining: 37.6s
4:	learn: 0.6394984	total: 61.6ms	remaining: 30.7s
5:	learn: 0.6286073	total: 62.6ms	remaining: 26s
6:	learn: 0.6182668	total: 63.8ms	remaining: 22.7s
7:	learn: 0.6097358	total: 64.8ms	remaining: 20.2s
8:	learn: 0.6001004	total: 65.7ms	remaining: 18.2s
9:	learn: 0.5909348	total: 66.7ms	remaining: 16.6s
10:	learn: 0.5824652	total: 67.7ms	remaining: 15.3s
11:	learn: 0.5724532	total: 68.7ms	remaining: 14.2s
12:	learn: 0.5634123	total: 69.6ms	remaining: 13.3s
13:	learn: 0.5553877	total: 70.6ms	remaining: 12.5s
14:	learn: 0.5474500	total: 71.7ms	remaining: 11.9s
15:	learn: 0.5400555	total: 72.8ms	remaining: 11.3s
16:	learn: 0.5308499	total: 73.9ms	remaining: 10.8s
17:	learn: 0.5231950	total: 74.8ms	remaining: 10.3s
18:	learn: 0.5159987	total: 75.8ms	remaining: 9.89s
19:	learn: 0.5094843	total: 77ms	remaining: 9.54s
20:	learn: 0.5028359	total: 78ms	remaining: 9.2s
21:	learn: 0.4956124	total: 79.2ms	remaining: 8.93s
22:	learn: 0.4895031	total: 80.4ms	remaining: 8.65s
23:	learn: 0.4821981	total: 81.4ms	remaining: 8.4s
24:	learn: 0.4764451	total: 82.5ms	remaining: 8.17s
25:	learn: 0.4701320	total: 83.6ms	remaining: 7.95s
26:	learn: 0.4643508	total: 84.7ms	remaining: 7.76s
27:	learn: 0.4577914	total: 85.7ms	remaining: 7.56s
28:	learn: 0.4509077	total: 86.6ms	remaining: 7.38s
29:	learn: 0.4453842	total: 88.1ms	remaining: 7.25s
30:	learn: 0.4390824	total: 89.2ms	remaining: 7.1s
31:	learn: 0.4331459	total: 90.2ms	remaining: 6.95s
32:	learn: 0.4278709	total: 91.2ms	remaining: 6.82s
33:	learn: 0.4238263	total: 92.4ms	remaining: 6.7s
34:	learn: 0.4188255	total: 93.5ms	remaining: 6.58s
35:	learn: 0.4137246	total: 94.4ms	remaining: 6.46s
36:	learn: 0.4089904	total: 95.4ms	remaining: 6.35s
37:	learn: 0.4039175	total: 96.6ms	remaining: 6.26s
38:	learn: 0.3992823	total: 97.6ms	remaining: 6.16s
39:	learn: 0.3949441	total: 98.7ms	remaining: 6.07s
40:	learn: 0.3896847	total: 99.7ms	remaining: 5.98s
41:	learn: 0.3849969	total: 101ms	remaining: 5.91s
42:	learn: 0.3801503	total: 102ms	remaining: 5.82s
43:	learn: 0.3763078	total: 103ms	remaining: 5.75s
44:	learn: 0.3722348	total: 104ms	remaining: 5.67s
45:	learn: 0.3686587	total: 105ms	remaining: 5.61s
46:	learn: 0.3647593	total: 107ms	remaining: 5.57s
47:	learn: 0.3611347	total: 108ms	remaining: 5.5s
48:	learn: 0.3577827	total: 109ms	remaining: 5.44s
49:	learn: 0.3543703	total: 110ms	remaining: 5.38s
50:	learn: 0.3504249	total: 111ms	remaining: 5.32s
51:	learn: 0.3470513	total: 112ms	remaining: 5.28s
52:	learn: 0.3434008	total: 113ms	remaining: 5.23s
53:	learn: 0.3402709	total: 114ms	remaining: 5.18s
54:	learn: 0.3370933	total: 116ms	remaining: 5.13s
55:	learn: 0.3338257	total: 116ms	remaining: 5.08s
56:	learn: 0.3312008	total: 118ms	remaining: 5.04s
57:	learn: 0.3279215	total: 118ms	remaining: 4.99s
58:	learn: 0.3252637	total: 120ms	remaining: 4.96s
59:	learn: 0.3221669	total: 121ms	remaining: 4.91s
60:	learn: 0.3196217	total: 122ms	remaining: 4.88s
61:	learn: 0.3171784	total: 123ms	remaining: 4.84s
62:	learn: 0.3150504	total: 124ms	remaining: 4.8s
63:	learn: 0.3127355	total: 125ms	remaining: 4.76s
64:	learn: 0.3099897	total: 126ms	remaining: 4.73s
65:	learn: 0.3073882	total: 127ms	remaining: 4.7s
66:	learn: 0.3050250	total: 129ms	remaining: 4.67s
67:	learn: 0.3027566	total: 130ms	remaining: 4.63s
68:	learn: 0.3003472	total: 131ms	remaining: 4.6s
69:	learn: 0.2979851	total: 131ms	remaining: 4.56s
70:	learn: 0.2960456	total: 133ms	remaining: 4.54s
71:	learn: 0.2938554	total: 134ms	remaining: 4.51s
72:	learn: 0.2916581	total: 135ms	remaining: 4.48s
73:	learn: 0.2896839	total: 136ms	remaining: 4.45s
74:	learn: 0.2878147	total: 137ms	remaining: 4.42s
75:	learn: 0.2860166	total: 138ms	remaining: 4.4s
76:	learn: 0.2842222	total: 139ms	remaining: 4.37s
77:	learn: 0.2820073	total: 140ms	remaining: 4.34s
78:	learn: 0.2801256	total: 141ms	remaining: 4.32s
79:	learn: 0.2783802	total: 142ms	remaining: 4.29s
80:	learn: 0.2763899	total: 143ms	remaining: 4.27s
81:	learn: 0.2746320	total: 145ms	remaining: 4.26s
82:	learn: 0.2730533	total: 146ms	remaining: 4.24s
83:	learn: 0.2716248	total: 147ms	remaining: 4.22s
84:	learn: 0.2702870	total: 148ms	remaining: 4.2s
85:	learn: 0.2688424	total: 149ms	remaining: 4.17s
86:	learn: 0.2672481	total: 150ms	remaining: 4.15s
87:	learn: 0.2656221	total: 151ms	remaining: 4.13s
88:	learn: 0.2639656	total: 152ms	remaining: 4.11s
89:	learn: 0.2625501	total: 153ms	remaining: 4.09s
90:	learn: 0.2608114	total: 154ms	remaining: 4.07s
91:	learn: 0.2592908	total: 155ms	remaining: 4.05s
92:	learn: 0.2577662	total: 156ms	remaining: 4.04s
93:	learn: 0.2562246	total: 157ms	remaining: 4.01s
94:	learn: 0.2550260	total: 158ms	remaining: 4s
95:	learn: 0.2538526	total: 159ms	remaining: 3.98s
96:	learn: 0.2524685	total: 160ms	remaining: 3.97s
97:	learn: 0.2513795	total: 161ms	remaining: 3.95s
98:	learn: 0.2503705	total: 162ms	remaining: 3.94s
99:	learn: 0.2490027	total: 163ms	remaining: 3.92s
100:	learn: 0.2478129	total: 164ms	remaining: 3.9s
101:	learn: 0.2465942	total: 166ms	remaining: 3.89s
102:	learn: 0.2455816	total: 167ms	remaining: 3.88s
103:	learn: 0.2445665	total: 168ms	remaining: 3.86s
104:	learn: 0.2435776	total: 169ms	remaining: 3.85s
105:	learn: 0.2426623	total: 170ms	remaining: 3.83s
106:	learn: 0.2417470	total: 171ms	remaining: 3.82s
107:	learn: 0.2406817	total: 172ms	remaining: 3.81s
108:	learn: 0.2396503	total: 173ms	remaining: 3.79s
109:	learn: 0.2386088	total: 174ms	remaining: 3.78s
110:	learn: 0.2374701	total: 175ms	remaining: 3.77s
111:	learn: 0.2365560	total: 176ms	remaining: 3.75s
112:	learn: 0.2355394	total: 177ms	remaining: 3.74s
113:	learn: 0.2347121	total: 178ms	remaining: 3.73s
114:	learn: 0.2339413	total: 179ms	remaining: 3.71s
115:	learn: 0.2329932	total: 180ms	remaining: 3.71s
116:	learn: 0.2320036	total: 182ms	remaining: 3.7s
117:	learn: 0.2309983	total: 183ms	remaining: 3.68s
118:	learn: 0.2303239	total: 184ms	remaining: 3.68s
119:	learn: 0.2295220	total: 185ms	remaining: 3.67s
120:	learn: 0.2286909	total: 186ms	remaining: 3.65s
121:	learn: 0.2278979	total: 187ms	remaining: 3.64s
122:	learn: 0.2272355	total: 188ms	remaining: 3.63s
123:	learn: 0.2264786	total: 189ms	remaining: 3.62s
124:	learn: 0.2256817	total: 190ms	remaining: 3.61s
125:	learn: 0.2248990	total: 191ms	remaining: 3.6s
126:	learn: 0.2242194	total: 192ms	remaining: 3.58s
127:	learn: 0.2234865	total: 193ms	remaining: 3.58s
128:	learn: 0.2225709	total: 194ms	remaining: 3.57s
129:	learn: 0.2219659	total: 196ms	remaining: 3.57s
130:	learn: 0.2212581	total: 197ms	remaining: 3.56s
131:	learn: 0.2204473	total: 198ms	remaining: 3.55s
132:	learn: 0.2198809	total: 199ms	remaining: 3.54s
133:	learn: 0.2193385	total: 200ms	remaining: 3.53s
134:	learn: 0.2187224	total: 201ms	remaining: 3.52s
135:	learn: 0.2179286	total: 202ms	remaining: 3.51s
136:	learn: 0.2172668	total: 203ms	remaining: 3.5s
137:	learn: 0.2166666	total: 204ms	remaining: 3.5s
138:	learn: 0.2160336	total: 205ms	remaining: 3.48s
139:	learn: 0.2152699	total: 206ms	remaining: 3.48s
140:	learn: 0.2148292	total: 207ms	remaining: 3.46s
141:	learn: 0.2142690	total: 208ms	remaining: 3.46s
142:	learn: 0.2136672	total: 210ms	remaining: 3.45s
143:	learn: 0.2130694	total: 211ms	remaining: 3.45s
144:	learn: 0.2124647	total: 212ms	remaining: 3.44s
145:	learn: 0.2119516	total: 213ms	remaining: 3.43s
146:	learn: 0.2112480	total: 214ms	remaining: 3.42s
147:	learn: 0.2108369	total: 215ms	remaining: 3.41s
148:	learn: 0.2104032	total: 216ms	remaining: 3.4s
149:	learn: 0.2100131	total: 217ms	remaining: 3.4s
150:	learn: 0.2095985	total: 218ms	remaining: 3.39s
151:	learn: 0.2091614	total: 219ms	remaining: 3.38s
152:	learn: 0.2085148	total: 220ms	remaining: 3.37s
153:	learn: 0.2081135	total: 221ms	remaining: 3.37s
154:	learn: 0.2076679	total: 223ms	remaining: 3.37s
155:	learn: 0.2070713	total: 224ms	remaining: 3.36s
156:	learn: 0.2066786	total: 224ms	remaining: 3.35s
157:	learn: 0.2062302	total: 226ms	remaining: 3.34s
158:	learn: 0.2058637	total: 227ms	remaining: 3.34s
159:	learn: 0.2054462	total: 228ms	remaining: 3.33s
160:	learn: 0.2050785	total: 229ms	remaining: 3.32s
161:	learn: 0.2045680	total: 230ms	remaining: 3.31s
162:	learn: 0.2041551	total: 231ms	remaining: 3.31s
163:	learn: 0.2037489	total: 231ms	remaining: 3.3s
164:	learn: 0.2033947	total: 232ms	remaining: 3.29s
165:	learn: 0.2029128	total: 234ms	remaining: 3.29s
166:	learn: 0.2025340	total: 235ms	remaining: 3.28s
167:	learn: 0.2021445	total: 236ms	remaining: 3.28s
168:	learn: 0.2016770	total: 237ms	remaining: 3.27s
169:	learn: 0.2013495	total: 238ms	remaining: 3.27s
170:	learn: 0.2010571	total: 239ms	remaining: 3.26s
171:	learn: 0.2007554	total: 240ms	remaining: 3.25s
172:	learn: 0.2003582	total: 242ms	remaining: 3.25s
173:	learn: 0.2000479	total: 243ms	remaining: 3.25s
174:	learn: 0.1997491	total: 244ms	remaining: 3.24s
175:	learn: 0.1994123	total: 245ms	remaining: 3.24s
176:	learn: 0.1991995	total: 247ms	remaining: 3.25s
177:	learn: 0.1988463	total: 249ms	remaining: 3.25s
178:	learn: 0.1984882	total: 251ms	remaining: 3.25s
179:	learn: 0.1981829	total: 252ms	remaining: 3.25s
180:	learn: 0.1979571	total: 254ms	remaining: 3.26s
181:	learn: 0.1975748	total: 257ms	remaining: 3.27s
182:	learn: 0.1972532	total: 259ms	remaining: 3.28s
183:	learn: 0.1969842	total: 260ms	remaining: 3.27s
184:	learn: 0.1966301	total: 262ms	remaining: 3.27s
185:	learn: 0.1963222	total: 263ms	remaining: 3.27s
186:	learn: 0.1959285	total: 264ms	remaining: 3.27s
187:	learn: 0.1956740	total: 266ms	remaining: 3.27s
188:	learn: 0.1953787	total: 267ms	remaining: 3.27s
189:	learn: 0.1951756	total: 269ms	remaining: 3.27s
190:	learn: 0.1948360	total: 271ms	remaining: 3.27s
191:	learn: 0.1946142	total: 272ms	remaining: 3.27s
192:	learn: 0.1943898	total: 273ms	remaining: 3.27s
193:	learn: 0.1941747	total: 274ms	remaining: 3.26s
194:	learn: 0.1938474	total: 276ms	remaining: 3.26s
195:	learn: 0.1934803	total: 277ms	remaining: 3.25s
196:	learn: 0.1932333	total: 278ms	remaining: 3.25s
197:	learn: 0.1930448	total: 279ms	remaining: 3.24s
198:	learn: 0.1928550	total: 280ms	remaining: 3.23s
199:	learn: 0.1925989	total: 281ms	remaining: 3.23s
200:	learn: 0.1924256	total: 282ms	remaining: 3.22s
201:	learn: 0.1921706	total: 283ms	remaining: 3.21s
202:	learn: 0.1918898	total: 284ms	remaining: 3.21s
203:	learn: 0.1917087	total: 285ms	remaining: 3.2s
204:	learn: 0.1914313	total: 286ms	remaining: 3.2s
205:	learn: 0.1911694	total: 287ms	remaining: 3.19s
206:	learn: 0.1909081	total: 288ms	remaining: 3.19s
207:	learn: 0.1906585	total: 289ms	remaining: 3.18s
208:	learn: 0.1904411	total: 290ms	remaining: 3.18s
209:	learn: 0.1902578	total: 300ms	remaining: 3.27s
210:	learn: 0.1900656	total: 306ms	remaining: 3.31s
211:	learn: 0.1897977	total: 315ms	remaining: 3.4s
212:	learn: 0.1895489	total: 324ms	remaining: 3.48s
213:	learn: 0.1893402	total: 329ms	remaining: 3.51s
214:	learn: 0.1891207	total: 332ms	remaining: 3.53s
215:	learn: 0.1889524	total: 336ms	remaining: 3.55s
216:	learn: 0.1887776	total: 340ms	remaining: 3.58s
217:	learn: 0.1886143	total: 356ms	remaining: 3.72s
218:	learn: 0.1884205	total: 360ms	remaining: 3.75s
219:	learn: 0.1882249	total: 365ms	remaining: 3.78s
220:	learn: 0.1880519	total: 368ms	remaining: 3.79s
221:	learn: 0.1878383	total: 369ms	remaining: 3.79s
222:	learn: 0.1876326	total: 371ms	remaining: 3.79s
223:	learn: 0.1874979	total: 372ms	remaining: 3.78s
224:	learn: 0.1873296	total: 373ms	remaining: 3.77s
225:	learn: 0.1871531	total: 375ms	remaining: 3.77s
226:	learn: 0.1869237	total: 376ms	remaining: 3.77s
227:	learn: 0.1867734	total: 378ms	remaining: 3.77s
228:	learn: 0.1865878	total: 380ms	remaining: 3.76s
229:	learn: 0.1863742	total: 381ms	remaining: 3.75s
230:	learn: 0.1861363	total: 382ms	remaining: 3.75s
231:	learn: 0.1859291	total: 383ms	remaining: 3.74s
232:	learn: 0.1857069	total: 384ms	remaining: 3.73s
233:	learn: 0.1855896	total: 385ms	remaining: 3.73s
234:	learn: 0.1853864	total: 386ms	remaining: 3.72s
235:	learn: 0.1852097	total: 391ms	remaining: 3.75s
236:	learn: 0.1849804	total: 396ms	remaining: 3.78s
237:	learn: 0.1848139	total: 398ms	remaining: 3.78s
238:	learn: 0.1846532	total: 399ms	remaining: 3.77s
239:	learn: 0.1844551	total: 400ms	remaining: 3.77s
240:	learn: 0.1843078	total: 401ms	remaining: 3.76s
241:	learn: 0.1841590	total: 402ms	remaining: 3.75s
242:	learn: 0.1840021	total: 404ms	remaining: 3.75s
243:	learn: 0.1837818	total: 405ms	remaining: 3.74s
244:	learn: 0.1836124	total: 406ms	remaining: 3.73s
245:	learn: 0.1834192	total: 406ms	remaining: 3.72s
246:	learn: 0.1832549	total: 408ms	remaining: 3.72s
247:	learn: 0.1831014	total: 409ms	remaining: 3.71s
248:	learn: 0.1829798	total: 410ms	remaining: 3.7s
249:	learn: 0.1828092	total: 411ms	remaining: 3.7s
250:	learn: 0.1826397	total: 412ms	remaining: 3.69s
251:	learn: 0.1824873	total: 413ms	remaining: 3.69s
252:	learn: 0.1823615	total: 414ms	remaining: 3.68s
253:	learn: 0.1822352	total: 415ms	remaining: 3.67s
254:	learn: 0.1820779	total: 416ms	remaining: 3.67s
255:	learn: 0.1819368	total: 417ms	remaining: 3.66s
256:	learn: 0.1817840	total: 418ms	remaining: 3.65s
257:	learn: 0.1816542	total: 419ms	remaining: 3.64s
258:	learn: 0.1815399	total: 420ms	remaining: 3.64s
259:	learn: 0.1813406	total: 421ms	remaining: 3.63s
260:	learn: 0.1812062	total: 422ms	remaining: 3.62s
261:	learn: 0.1810354	total: 423ms	remaining: 3.62s
262:	learn: 0.1809035	total: 425ms	remaining: 3.61s
263:	learn: 0.1807517	total: 426ms	remaining: 3.6s
264:	learn: 0.1806111	total: 427ms	remaining: 3.6s
265:	learn: 0.1804976	total: 428ms	remaining: 3.59s
266:	learn: 0.1803679	total: 429ms	remaining: 3.58s
267:	learn: 0.1802371	total: 430ms	remaining: 3.58s
268:	learn: 0.1801170	total: 431ms	remaining: 3.57s
269:	learn: 0.1800016	total: 432ms	remaining: 3.56s
270:	learn: 0.1798890	total: 433ms	remaining: 3.56s
271:	learn: 0.1797273	total: 434ms	remaining: 3.55s
272:	learn: 0.1795998	total: 435ms	remaining: 3.55s
273:	learn: 0.1794178	total: 436ms	remaining: 3.54s
274:	learn: 0.1793276	total: 437ms	remaining: 3.53s
275:	learn: 0.1792072	total: 438ms	remaining: 3.53s
276:	learn: 0.1791084	total: 439ms	remaining: 3.52s
277:	learn: 0.1789477	total: 440ms	remaining: 3.52s
278:	learn: 0.1788311	total: 441ms	remaining: 3.51s
279:	learn: 0.1787557	total: 442ms	remaining: 3.5s
280:	learn: 0.1786299	total: 443ms	remaining: 3.5s
281:	learn: 0.1785242	total: 444ms	remaining: 3.49s
282:	learn: 0.1783640	total: 445ms	remaining: 3.48s
283:	learn: 0.1782796	total: 446ms	remaining: 3.48s
284:	learn: 0.1781953	total: 447ms	remaining: 3.47s
285:	learn: 0.1780537	total: 448ms	remaining: 3.47s
286:	learn: 0.1779587	total: 449ms	remaining: 3.46s
287:	learn: 0.1778391	total: 450ms	remaining: 3.46s
288:	learn: 0.1777391	total: 451ms	remaining: 3.45s
289:	learn: 0.1776389	total: 452ms	remaining: 3.44s
290:	learn: 0.1775284	total: 453ms	remaining: 3.44s
291:	learn: 0.1774252	total: 454ms	remaining: 3.43s
292:	learn: 0.1773067	total: 455ms	remaining: 3.43s
293:	learn: 0.1772324	total: 456ms	remaining: 3.42s
294:	learn: 0.1771248	total: 457ms	remaining: 3.42s
295:	learn: 0.1770266	total: 458ms	remaining: 3.41s
296:	learn: 0.1769061	total: 459ms	remaining: 3.41s
297:	learn: 0.1767720	total: 460ms	remaining: 3.4s
298:	learn: 0.1766686	total: 461ms	remaining: 3.4s
299:	learn: 0.1765599	total: 462ms	remaining: 3.39s
300:	learn: 0.1764701	total: 463ms	remaining: 3.38s
301:	learn: 0.1763720	total: 464ms	remaining: 3.38s
302:	learn: 0.1762722	total: 466ms	remaining: 3.38s
303:	learn: 0.1761938	total: 467ms	remaining: 3.37s
304:	learn: 0.1761012	total: 468ms	remaining: 3.37s
305:	learn: 0.1759891	total: 469ms	remaining: 3.36s
306:	learn: 0.1758454	total: 470ms	remaining: 3.35s
307:	learn: 0.1757867	total: 471ms	remaining: 3.35s
308:	learn: 0.1756734	total: 472ms	remaining: 3.35s
309:	learn: 0.1756040	total: 473ms	remaining: 3.34s
310:	learn: 0.1755198	total: 474ms	remaining: 3.33s
311:	learn: 0.1754431	total: 475ms	remaining: 3.33s
312:	learn: 0.1753591	total: 476ms	remaining: 3.33s
313:	learn: 0.1752442	total: 477ms	remaining: 3.32s
314:	learn: 0.1751461	total: 478ms	remaining: 3.32s
315:	learn: 0.1750605	total: 479ms	remaining: 3.31s
316:	learn: 0.1749722	total: 480ms	remaining: 3.31s
317:	learn: 0.1748929	total: 481ms	remaining: 3.3s
318:	learn: 0.1747701	total: 482ms	remaining: 3.3s
319:	learn: 0.1746828	total: 483ms	remaining: 3.29s
320:	learn: 0.1746131	total: 484ms	remaining: 3.29s
321:	learn: 0.1745349	total: 486ms	remaining: 3.29s
322:	learn: 0.1744191	total: 487ms	remaining: 3.28s
323:	learn: 0.1743010	total: 488ms	remaining: 3.28s
324:	learn: 0.1742185	total: 489ms	remaining: 3.27s
325:	learn: 0.1741066	total: 490ms	remaining: 3.27s
326:	learn: 0.1740245	total: 491ms	remaining: 3.26s
327:	learn: 0.1739581	total: 492ms	remaining: 3.26s
328:	learn: 0.1738776	total: 493ms	remaining: 3.25s
329:	learn: 0.1737721	total: 494ms	remaining: 3.25s
330:	learn: 0.1736672	total: 495ms	remaining: 3.24s
331:	learn: 0.1735652	total: 496ms	remaining: 3.24s
332:	learn: 0.1734992	total: 497ms	remaining: 3.23s
333:	learn: 0.1734199	total: 498ms	remaining: 3.23s
334:	learn: 0.1733357	total: 499ms	remaining: 3.22s
335:	learn: 0.1732218	total: 500ms	remaining: 3.22s
336:	learn: 0.1731568	total: 501ms	remaining: 3.21s
337:	learn: 0.1730801	total: 502ms	remaining: 3.21s
338:	learn: 0.1729988	total: 503ms	remaining: 3.21s
339:	learn: 0.1728958	total: 504ms	remaining: 3.2s
340:	learn: 0.1728104	total: 505ms	remaining: 3.2s
341:	learn: 0.1727589	total: 506ms	remaining: 3.19s
342:	learn: 0.1726655	total: 507ms	remaining: 3.19s
343:	learn: 0.1725760	total: 508ms	remaining: 3.18s
344:	learn: 0.1724922	total: 509ms	remaining: 3.18s
345:	learn: 0.1724179	total: 510ms	remaining: 3.17s
346:	learn: 0.1723308	total: 511ms	remaining: 3.17s
347:	learn: 0.1722440	total: 512ms	remaining: 3.17s
348:	learn: 0.1721621	total: 513ms	remaining: 3.16s
349:	learn: 0.1720365	total: 514ms	remaining: 3.16s
350:	learn: 0.1719549	total: 515ms	remaining: 3.15s
351:	learn: 0.1719121	total: 516ms	remaining: 3.15s
352:	learn: 0.1718445	total: 517ms	remaining: 3.14s
353:	learn: 0.1717549	total: 518ms	remaining: 3.14s
354:	learn: 0.1716984	total: 519ms	remaining: 3.13s
355:	learn: 0.1716387	total: 520ms	remaining: 3.13s
356:	learn: 0.1715824	total: 521ms	remaining: 3.13s
357:	learn: 0.1715216	total: 522ms	remaining: 3.13s
358:	learn: 0.1714608	total: 523ms	remaining: 3.12s
359:	learn: 0.1713980	total: 524ms	remaining: 3.12s
360:	learn: 0.1713257	total: 525ms	remaining: 3.11s
361:	learn: 0.1712619	total: 526ms	remaining: 3.11s
362:	learn: 0.1711693	total: 527ms	remaining: 3.1s
363:	learn: 0.1711160	total: 528ms	remaining: 3.1s
364:	learn: 0.1710029	total: 529ms	remaining: 3.1s
365:	learn: 0.1708933	total: 530ms	remaining: 3.09s
366:	learn: 0.1708002	total: 531ms	remaining: 3.09s
367:	learn: 0.1707318	total: 532ms	remaining: 3.08s
368:	learn: 0.1706458	total: 533ms	remaining: 3.08s
369:	learn: 0.1705925	total: 534ms	remaining: 3.08s
370:	learn: 0.1705106	total: 535ms	remaining: 3.07s
371:	learn: 0.1704298	total: 536ms	remaining: 3.07s
372:	learn: 0.1703703	total: 537ms	remaining: 3.06s
373:	learn: 0.1703286	total: 538ms	remaining: 3.06s
374:	learn: 0.1702517	total: 539ms	remaining: 3.06s
375:	learn: 0.1701891	total: 540ms	remaining: 3.05s
376:	learn: 0.1701194	total: 541ms	remaining: 3.05s
377:	learn: 0.1700414	total: 542ms	remaining: 3.04s
378:	learn: 0.1700016	total: 543ms	remaining: 3.04s
379:	learn: 0.1699294	total: 544ms	remaining: 3.04s
380:	learn: 0.1698371	total: 545ms	remaining: 3.03s
381:	learn: 0.1697909	total: 546ms	remaining: 3.03s
382:	learn: 0.1697324	total: 547ms	remaining: 3.02s
383:	learn: 0.1696518	total: 548ms	remaining: 3.02s
384:	learn: 0.1695858	total: 549ms	remaining: 3.02s
385:	learn: 0.1695269	total: 550ms	remaining: 3.01s

{'Accuracy': 0.9212598425196851,
 'Precision': 0.8982035928143712,
 'Recall': 0.9202453987730062,
 'AUC-ROC': 0.9770923622446108,
 'F1-score': 0.9090909090909091,
 'True Positive': np.int64(150),
 'True Negative': np.int64(201),
 'False Positive': np.int64(17),
 'False Negative': np.int64(13),
 'True Negative Rate (Specificity)': np.float64(0.9220183486238532),
 'Negative Predictive Value': np.float64(0.9392523364485982),
 'False Positive Rate': np.float64(0.0779816513761468),
 'False Discovery Rate': np.float64(0.10179640718562874)}